### ISSUE TITLE
Problem with another dashboard

### ISSUE THREAD

**Issue by kaipi55** [cnorick/ha-auto-guest-login#7]
Hi , i am a new home assistant user and I have integrated a guest dashboard (made with https://github.com/resoai/TileBoard) in the "www" folder, and it is accessed with "http://HASS_IP:8123/local/tileboard/index.html". My question is: Is there any way to redirect the guest to that dashboard or is it only compatible with lovelace? 

(Pd: thanks for your dedication c: )

**Comment by cnorick** [comment]
Yes, that should work fine. I imagine since it's in the www, you can skip the login part (although it doesn't hurt to leave it). All you would have to do is change the dashboard variable to be everything past the first '/'. So in your case: 'local/tileboard/index.html'.

**Comment by kaipi55** [comment]
I typed "local/tileboard/index.html" in DASH but after loading the page that says "Thanks for Visiting" you only see a "404: Not Found". do you have any idea what could be wrong or what am I doing wrong?

**Comment by cnorick** [comment]
Hmmm, looking at it again, I think maybe what I said wouldn't work as-is. I think the problem is that the server code encodes the dashboard when it creates the redirect URI:
```
function createRedirectUri(code) {
  let uri = `${haUrl}/${encodeURIComponent(dashboard)}?auth_callback=1`;
```

When it encodes your dashboard uri, it converts the slashes to `%2F`, and so the browser probably doesn't interpret it correctly when it gets redirected.

When you get the 404 page, what do you see in the address bar? If you are seeing the `%2F`s you might try modifying the code locally to remove the `encodeURIComponent` part.

Alternatively, if you'd rather not make code changes, you could consider making a home assistant dashboard that contains a link to your other one (I know that's probably not ideal).
